### ISSUE TITLE
[Crash] [1.20.1] Rendering straw statue from Straw Statues mod crashes due to a faulty cast from an EMF mixin

### ISSUE THREAD

**Issue by Fuzss** [Traben-0/Entity_Model_Features#334]
https://github.com/Fuzss/strawstatues/issues/51

```
java.lang.ClassCastException: class fuzs.strawstatues.world.entity.decoration.StrawStatue cannot be cast to class net.minecraft.world.entity.player.Player (fuzs.strawstatues.world.entity.decoration.StrawStatue is in module strawstatues@8.0.3 of loader 'TRANSFORMER' @5ac8916d; net.minecraft.world.entity.player.Player is in module minecraft@1.20.1 of loader 'TRANSFORMER' @5ac8916d)
	at net.minecraft.client.model.PlayerModel.handler$bfd000$entity_model_features$emf$RenderCustomModelOnly(PlayerModel.java:4062) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.model.PlayerModel.m_103411_(PlayerModel.java) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
	at fuzs.strawstatues.client.renderer.entity.layers.StrawStatueCapeLayer.render(StrawStatueCapeLayer.java:68) ~[StrawStatues-v8.0.3-1.20.1-Forge.jar%23346!/:8.0.3] {re:classloading}
	at fuzs.strawstatues.client.renderer.entity.layers.StrawStatueCapeLayer.m_6494_(StrawStatueCapeLayer.java:24) ~[StrawStatues-v8.0.3-1.20.1-Forge.jar%23346!/:8.0.3] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.redirect$zei000$apoli$preventFeatureRendering(LivingEntityRenderer.java:1099) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:client.renderer.entity.MixinRendererLivingEntity from mod (unknown),pl:mixin:APP:apoli.mixins.json:LivingEntityRendererMixin from mod apoli,pl:mixin:APP:citadel.mixins.json:client.LivingEntityRendererMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:safety.LivingEntityRendererMixin from mod modernfix,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_pose_stack.LivingEntityRendererMixin from mod modernfix,pl:mixin:APP:railways-common.mixins.json:client.AccessorLivingEntityRenderer from mod railways,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinLivingEntityRenderer from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.renderer.MixinLivingEntityRenderer from mod entity_texture_features,pl:mixin:APP:mobplayeranimator.mixins.json:client.LivingEntityRendererMixin from mod mobplayeranimator,pl:mixin:APP:nyfsspiders.mixins.json:MixinLivingRenderer from mod nyfsspiders,pl:mixin:APP:alexscaves.mixins.json:client.LivingEntityRendererMixin from mod alexscaves,pl:mixin:APP:apugli.mixins.json:client.LivingEntityRendererMixin from mod apugli,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.LivingEntityRendererMixin from mod playeranimator,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.model.MixinArmadilloModel from mod entity_model_features,pl:mixin:APP:entity_model_features-optional.mixins.json:MixinLivingEntityRenderer_ValueCapturing from mod entity_model_features,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:131) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:client.renderer.entity.MixinRendererLivingEntity from mod (unknown),pl:mixin:APP:apoli.mixins.json:LivingEntityRendererMixin from mod apoli,pl:mixin:APP:citadel.mixins.json:client.LivingEntityRendererMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:safety.LivingEntityRendererMixin from mod modernfix,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_pose_stack.LivingEntityRendererMixin from mod modernfix,pl:mixin:APP:railways-common.mixins.json:client.AccessorLivingEntityRenderer from mod railways,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinLivingEntityRenderer from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.renderer.MixinLivingEntityRenderer from mod entity_texture_features,pl:mixin:APP:mobplayeranimator.mixins.json:client.LivingEntityRendererMixin from mod mobplayeranimator,pl:mixin:APP:nyfsspiders.mixins.json:MixinLivingRenderer from mod nyfsspiders,pl:mixin:APP:alexscaves.mixins.json:client.LivingEntityRendererMixin from mod alexscaves,pl:mixin:APP:apugli.mixins.json:client.LivingEntityRendererMixin from mod apugli,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.LivingEntityRendererMixin from mod playeranimator,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.model.MixinArmadilloModel from mod entity_model_features,pl:mixin:APP:entity_model_features-optional.mixins.json:MixinLivingEntityRenderer_ValueCapturing from mod entity_model_features,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at fuzs.strawstatues.client.renderer.entity.StrawStatueRenderer.render(StrawStatueRenderer.java:60) ~[StrawStatues-v8.0.3-1.20.1-Forge.jar%23346!/:8.0.3] {re:classloading}
	at fuzs.strawstatues.client.renderer.entity.StrawStatueRenderer.m_7392_(StrawStatueRenderer.java:32) ~[StrawStatues-v8.0.3-1.20.1-Forge.jar%23346!/:8.0.3] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1440) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1223) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:apoli.mixins.json:GameRendererMixin from mod apoli,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer from mod railways,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom from mod (unknown),pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority_Pre from mod (unknown),pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent from mod (unknown),pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin from mod tacz,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:apugli.mixins.json:client.GameRendererMixin from mod apugli,pl:mixin:APP:apugli.mixins.json:client.accessor.GameRendererAccessor from mod apugli,pl:mixin:APP:apugli.forge.mixins.json:client.GameRendererMixin from mod apugli,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer from mod valkyrienskies,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:apoli.mixins.json:GameRendererMixin from mod apoli,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer from mod railways,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom from mod (unknown),pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority_Pre from mod (unknown),pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent from mod (unknown),pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin from mod tacz,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:apugli.mixins.json:client.GameRendererMixin from mod apugli,pl:mixin:APP:apugli.mixins.json:client.accessor.GameRendererAccessor from mod apugli,pl:mixin:APP:apugli.forge.mixins.json:client.GameRendererMixin from mod apugli,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer from mod valkyrienskies,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23352!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-47.3.29.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:mixins.emibridge.json:MainEntrypointMixin from mod connectorextras_emi_bridge,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.29.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.29.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.29.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by Fuzss** [comment]
Similar to #323.

**Comment by Fuzss** [comment]
Any update on this?

**Comment by M0onkeyZzz** [comment]
Hello !  Same case here, on neoforge 1.21.1, if the statue loads a skin containing a cape, the game crashes but not the server, if I disable all packs emf/etf, I can reconnect without problems 
I thought it was due to well-known names, but apparently it's coming from the capes

**Comment by Fuzss** [comment]
Hey @Traben-0, would you mind fixing this on your end? 
It's been a while and the issue remains very present, getting reports about it almost every other day.

**Comment by Traben-0** [comment]
this is already fixed for the next release which i plan to have out with or before 1.21.6

**Comment by Monkeyz33** [comment]
Any news ? Still here 5 month later on neoforge 1.21.1,  lot of bugs still here too and 1.21.6 is out , it's 1.21.8 now

**Comment by Traben-0** [comment]
do the latest dev builds on my discord not fix this?

**Comment by M0onkeyZzz** [comment]
This 2 devbuilds crash my game , the crash log : 

[CrashLog](https://pastebin.com/thV5Cpcm)

Returning to the latest versions of emf and etf on CurseForge resolves the crash

**Comment by Traben-0** [comment]
ok try with those new ones i jsut posted, looks like there were 2 bugs specifically affected both neoforge and 1.21.1 respectively

**Comment by Traben-0** [comment]
<img width="854" height="480" alt="Image" src="https://github.com/user-attachments/assets/c410e1fb-436a-4f28-bbb0-dcafe7cd831d" />

seems to be working just fine in my current dev setup that i'll be releasing tonight or tomorrow, the dev builds posted should be the exact same even if you can't find them

**Comment by Traben-0** [comment]
granted the last dev builds posted crash on 1.21.4 for an unrelated issue that i've fixed since then but not added new builds

**Comment by M0onkeyZzz** [comment]
[Since immediatelyfast there seems to be something else, reset to older build resolve the crash](https://mclo.gs/OJDgNZ3)

**Comment by Traben-0** [comment]
yes, they will need to update

**Comment by M0onkeyZzz** [comment]
After a few tests with Emotecraft disabled, everything seems to be working. Entering a character name with a cape no longer seems to crash the game, but the cape loads on the front of the character instead of on their back. This seems to happen with all skins that include a cape

[Photos](https://postimg.cc/gallery/km29nLZ)

**Comment by Fuzss** [comment]
> <img alt="Image" width="854" height="480" src="https://private-user-images.githubusercontent.com/8456487/481334867-c410e1fb-436a-4f28-bbb0-dcafe7cd831d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxMjE2ODUsIm5iZiI6MTc1NjEyMTM4NSwicGF0aCI6Ii84NDU2NDg3LzQ4MTMzNDg2Ny1jNDEwZTFmYi00MzZhLTRmMjgtYmJiMC1kY2FmZTdjZDgzMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA4MjVUMTEyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg5MzIwNDZhNjliMDU0MmU0ZmIwNjY0MzY4MzI2MzI0YmMzYmQzNmYwNGFkNzA4MjdkZWVkN2JhMDI4ZDE3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ag-39WxWTBCqxbBM2oKcCO0xT5MVNP_H5gLcf4_aarI">
> seems to be working just fine in my current dev setup that i'll be releasing tonight or tomorrow, the dev builds posted should be the exact same even if you can't find them

@Traben-0 

It's possible you need to set a skin on the straw statue that has a cape to reproduce the crash. 

To do that on this screen set a name for an account with a cape, like any of the Mojang employees, like `jeb_` or `Dinnerbone`.

**Comment by Traben-0** [comment]
The crash is sodium options mod expecting an older emf version
